
services:
  consul:
    image: consul:latest
    restart: always
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "consul agent -retry-join ${CONSUL_MASTER_IP} -advertise ${CURRENT_IP} -node ${CONSUL_NODE_NAME} -data-dir /tmp/data-dir -client 0.0.0.0 -ui"
  registrator:
    image: gliderlabs/registrator:latest
    restart: always
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: "-ip ${CURRENT_IP} consul://${CURRENT_IP}:8500"
  web:
    image: nginx:latest
    restart: always
    hostname: nginx
    ports:
      - "80"
    environment:
      SERVICE_NAME: web
